export const REQUEST_FETCH_TRAIL = 'REQUEST_FETCH_TRAIL';
export const CONFIRM_FETCH_TRAIL = 'CONFIRM_FETCH_TRAIL';
export const REJECT_FETCH_TRAIL = 'REJECT_FETCH_TRAIL';
export const CLEAR_TRAIL = 'CLEAR_TRAIL';

export const SET_ACTIVE_IMAGE = 'SET_ACTIVE_IMAGE';