export const REQUEST_LOAD_PRIMARY_TRAIL = 'REQUEST_LOAD_PRIMARY_TRAIL';
export const CONFIRM_LOAD_PRIMARY_TRAIL = 'CONFIRM_LOAD_PRIMARY_TRAIL';
export const CONFIRM_EXTEND_PRIMARY_TRAIL = 'CONFIRM_EXTEND_PRIMARY_TRAIL';

export const REQUEST_LOAD_RELATED_TRAILS = 'REQUEST_LOAD_RELATED_TRAILS';
export const CONFIRM_LOAD_RELATED_TRAILS = 'CONFIRM_LOAD_RELATED_TRAILS';